### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by quancs** [lbaby/codeGarden#1]
**python版本3.7.3**
PS D:\projects\ANKI> python --version
Python 3.7.3

**ModuleNotFoundError: No module named 'six'**
PS D:\projects\ANKI> type words.txt | python .\bing2anki.py .\voice\
Traceback (most recent call last):
  File ".\bing2anki.py", line 2, in <module>
    import splinter
  File "D:\Program Files\Python37\lib\site-packages\splinter\__init__.py", line 5, in <module>
    from splinter.browser import Browser  # NOQA
  File "D:\Program Files\Python37\lib\site-packages\splinter\browser.py", line 9, in <module>
    from splinter.driver.webdriver.firefox import WebDriver as FirefoxWebDriver
  File "D:\Program Files\Python37\lib\site-packages\splinter\driver\webdriver\__init__.py", line 16, in <module>
    from six import BytesIO
ModuleNotFoundError: No module named 'six'

**Comment by quancs** [comment]
解决问题：pip install 'six'

**Comment by quancs** [comment]
使用的时候，还有可能遇到的问题是chrome版本和chromeDriver版本不匹配，导致出现DriverException，解决方法就是换匹配的chrome或者chromeDriver
